"""
analysis.py
-----------
Unified production-ready response schemas for the completed EO Analysis pipeline.
These models represent the final API shapes returned to the frontend.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Any


class AnalysisMetadata(BaseModel):
    """
    Request-level provenance and performance metadata.
    Returned alongside every production AnalysisResponse.
    """
    vision_model: str = Field(..., description="RemoteCLIP model identifier used for inference.")
    llm_model: str = Field(..., description="GPT/LLM model identifier used for analysis.")
    report_model: Optional[str] = Field(None, description="Claude/Report model identifier used for generation.")
    processing_time_ms: float = Field(..., description="Total end-to-end pipeline time in milliseconds.")
    timestamp: str = Field(..., description="ISO-8601 UTC timestamp of when the request was processed.")
    version: str = Field(default="1.0", description="API response schema version.")
    latitude: Optional[float] = Field(None, description="Captured latitude coordinate.")
    longitude: Optional[float] = Field(None, description="Captured longitude coordinate.")
    bbox: Optional[List[float]] = Field(None, description="Captured bounding box bounds.")


class LandCoverClass(BaseModel):
    """A single classified land-cover category with color and percentage."""
    label: str
    pct: float
    color: str


class AnalysisFlag(BaseModel):
    """An informational, warning, or danger flag surfaced for the frontend."""
    icon: str
    label: str
    level: str  # "info" | "warning" | "danger"


class AnalysisResponse(BaseModel):
    """
    Unified production response for POST /api/analyze.

    Contains:
    - EO semantic classification (dominant/secondary land cover, confidence)
    - Rule-based scene summary from the interpreter
    - GPT-generated analyst report (or null with a warning if LLM unavailable)
    - Request metadata (model provenance, timing, timestamp)
    - Frontend-compatible fields: insight, classes, flags, title, risk_level

    Raw vision-layer internals (embeddings, cosine similarities, logits)
    are NOT included here — they remain exclusive to /api/vision/test.
    """
    # --- Pipeline status ---
    status: str = Field(
        ...,
        description="Pipeline outcome: 'success' or 'partial_success' (GPT unavailable)."
    )

    # --- EO Classification ---
    dominant_land_cover: str = Field(
        ...,
        description="The primary mapped Earth Observation category detected in the image."
    )
    secondary_land_cover: Optional[str] = Field(
        None,
        description="The secondary mapped category, or None if not applicable/undetermined."
    )
    confidence: str = Field(
        ...,
        description="Relative confidence qualitative band: High | Medium | Low."
    )
    summary: str = Field(
        ...,
        description="Rule-aligned static text summary generated from core semantics."
    )
    gpt_analysis: Optional[str] = Field(
        None,
        description="Reasoned interpretation report generated by GPT. Null if LLM failed."
    )
    professional_report: Optional[str] = Field(
        None,
        description="Professional Markdown report generated by Claude. Null if Claude failed."
    )
    warning: Optional[str] = Field(
        None,
        description="Present when status is 'partial_success'. Describes why GPT was skipped."
    )
    vegetation_health_score: Optional[float] = Field(
        None,
        description="Lightweight 0-100 vegetation health score proxy."
    )
    vegetation_health_disclaimer: Optional[str] = Field(
        None,
        description="Disclaimer explaining that this is an RGB-based proxy."
    )
    water_coverage_percent: Optional[float] = Field(
        None,
        description="OpenCV detected water extent coverage percentage."
    )
    water_mask_base64: Optional[str] = Field(
        None,
        description="Base64-encoded PNG image of transparent water mask."
    )
    flood_risk_score: Optional[float] = Field(
        None,
        description="Rule-based calculated flood risk score (0-100)."
    )
    flood_risk_label: Optional[str] = Field(
        None,
        description="Qualitative flood risk label: Low | Moderate | High | Severe."
    )
    flood_risk_reasoning: Optional[str] = Field(
        None,
        description="One-line reasoning explaining the flood risk assessment."
    )

    # --- Frontend-compatible fields (mirrors the existing UI contract) ---
    insight: str = Field(
        ...,
        description="Short human-readable insight shown in the chat UI (same as summary or GPT excerpt)."
    )
    classes: List[LandCoverClass] = Field(
        default_factory=list,
        description="Land-cover classes with percentage breakdown for the bar chart."
    )
    flags: List[AnalysisFlag] = Field(
        default_factory=list,
        description="Informational flags surfaced to the frontend UI."
    )
    title: Optional[str] = Field(
        None,
        description="Short title for the analysis report card."
    )
    risk_level: Optional[str] = Field(
        None,
        description="Qualitative risk level: Low | Medium | High."
    )
    latitude: Optional[float] = Field(None, description="Captured latitude coordinate.")
    longitude: Optional[float] = Field(None, description="Captured longitude coordinate.")
    bbox: Optional[List[float]] = Field(None, description="Captured bounding box bounds.")

    # --- Metadata ---
    metadata: AnalysisMetadata = Field(
        ...,
        description="Request-level provenance, model info, and performance metrics."
    )


class FloodComparisonResponse(BaseModel):
    """
    Response schema for POST /api/analyze/compare-flood.
    """
    before_water_coverage_percent: float = Field(..., description="Water coverage percentage in the before image.")
    after_water_coverage_percent: float = Field(..., description="Water coverage percentage in the after image.")
    water_coverage_change_percent: float = Field(..., description="Difference in water coverage (after - before).")
    classification: str = Field(..., description="Flood classification outcome based on change delta.")
    before_water_mask_base64: str = Field(..., description="Base64 encoded PNG water mask for the before image.")
    after_water_mask_base64: str = Field(..., description="Base64 encoded PNG water mask for the after image.")
